### ISSUE TITLE
Extract detected boxes

### ISSUE THREAD

**Issue by ghost** [ZhengPeng7/OCR_TIANCHI_ICPR#1]
@ZhengPeng7 
Now that I have detected the boxes `x1,y1,x2,y2,x3,y3,x4,y4`, how to extract and crop from the images?

**Comment by ZhengPeng7** [comment]
The direct array slicing just works, like `img[y1:y4+1, x1:x4+1]`.
BTW, I'm sorry that I don't remember the order of the 4 points, so you'd better try it by yourself.
